### Register Endpoint
POST http://localhost:8080/HelferServer/webapi/auth/register
Content-Type: application/json
Accept: application/json

{
  "name": "Bob",
  "vorname": "Dieter",
  "adresse": {
    "strasse": "Example Street",
    "hausnummer": 22,
    "stadt": "Example City",
    "plz": "12345"
  },
  "benutzergruppe": "MITGLIED",
  "email": "abc@gmail.com",
  "passwort": "SecurePass123!"
}

### Test the login endpoint
POST http://localhost:8080/HelferServer/webapi/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "abc@gmail.com",
  "passwort": "SecurePass123!"
}

### Test the create event endpoint
POST http://localhost:8080/HelferServer/webapi/event
Content-Type: application/json
Authentication: Bearer NDo5NjI5YmU1My05ZGJmLTQxYmUtYTVhZi1mZTQwMjk3NmQwZTY6RXZlbnRNYXN0ZXI=
Accept: application/json

{
  "name": "Community Clean-Up",
  "date": "2024-08-01T00:00:00",
  "helferListe": []
}

### Test the get event by ID endpoint
GET http://localhost:8080/HelferServer/webapi/event/3
Authentication: Bearer NDoyOTg4MjkzMS0yNzFkLTRkODAtYWY2MS1mZmJmYzVjNDFkODQ6RXZlbnRNYXN0ZXI=
Accept: application/json

### Test the get all events endpoint
GET http://localhost:8080/HelferServer/webapi/event
Accept: application/json

### Test the update event endpoint
PUT http://localhost:8080/HelferServer/webapi/event
Content-Type: application/json
Authentication: Bearer NDphY2RmN2M2OC1lMTZhLTRmYjgtYjE1Ni1mMzFjOWE2NWM2ZDE6RXZlbnRNYXN0ZXI=
Accept: application/json

{
  "id": 4,
  "name": "Updated Community Clean-Up 2",
  "date": "2024-08-02T00:00:00"
}

### Test the delete event endpoint
DELETE http://localhost:8080/HelferServer/webapi/event/3
Authentication: Bearer NDphY2RmN2M2OC1lMTZhLTRmYjgtYjE1Ni1mMzFjOWE2NWM2ZDE6RXZlbnRNYXN0ZXI=

### Test the add helfer endpoint
POST http://localhost:8080/HelferServer/webapi/event/9/helfer
Authentication: Bearer NTpjNzZiMTNlMi1mMzI1LTRlNzItOTcxNC1kNzE4MzY5YTc1Njk6RXZlbnRNYXN0ZXI=
Content-Type: application/json
Accept: application/json